## Contruindo  Graph

O TensorFlow funciona como um modelo computacional de gráfico. Vamos criar o nosso primeiro gráfico.
Para criar nosso primeiro gráfico, utilizaremos as operações de origem, que não precisam de entrada de informações. Essas operações de origem ou operações de origem passarão suas informações para outras operações que irão executar cálculos.
Para criar duas operações de origem que irão produzir números, definiremos duas constantes

In [20]:
import tensorflow as tf
import numpy as np

In [21]:
a = tf.constant(2)
b = tf.constant(3)

c = tf.add(a,b)



In [22]:
#Executando o calculo

Sess = tf.Session()
print(Sess.run(c))

Sess.close

5


<bound method BaseSession.close of <tensorflow.python.client.session.Session object at 0x7f3e9bd44be0>>

In [23]:
# Defining multidimensional arrays using TensorFlow

## Definindo matrizes multidimensionais usando TensorFlow

In [41]:
Scalar = tf.constant(5)
Vector = tf.constant([1,2,3])
Matrix = tf.constant([[1,2,3],[2,3,4],[6,7,8]])
Tesor =  tf.constant([[[1,2,3],[2,3,4],[3,4,5]] , [[4,5,6],[5,6,7],[6,7,8]],[[7,8,9],[8,9,10],[9,10,11]]])

modelo = tf.global_variables_initializer()

In [42]:
with tf.Session() as sess:
    sess.run(modelo)
    print('O Scalar  e {}   '.format(sess.run(Scalar)))
    print('O Vector e  1x3  = {}'.format(sess.run(Vector)))
    print('A Matrix 3x3 e \n{}'.format(sess.run(Matrix)))
    print('Tensor 3x3x3 \n\n e {}'.format(sess.run(Tesor)))

O Scalar  e 5   
O Vector e  1x3  = [1 2 3]
A Matrix 3x3 e 
[[1 2 3]
 [2 3 4]
 [6 7 8]]
Tensor 3x3x3 

 e [[[ 1  2  3]
  [ 2  3  4]
  [ 3  4  5]]

 [[ 4  5  6]
  [ 5  6  7]
  [ 6  7  8]]

 [[ 7  8  9]
  [ 8  9 10]
  [ 9 10 11]]]


In [43]:
#usando tensor flow (add)

In [45]:
Matri1 = tf.constant([[1,2,3],[2,3,4],[3,4,5]])#3x3
Matri2 = tf.constant([[4,4,4],[5,5,5],[6,6,6]])

#somar as matrizes

resultado = tf.add(Matri1,Matri2)

In [46]:
sess = tf.Session()
print('O resultado da soma e {}'.format(Sess.run(resultado)))

O resultado da soma e [[ 5  6  7]
 [ 7  8  9]
 [ 9 10 11]]


## Variables

Agora que estamos mais familiarizados com a estrutura de dados, analisaremos como o TensorFlow lida com as variáveis.
Para definir variáveis, usamos o comando __tf.variable ()__. Para poder usar variáveis em um gráfico de computação, é necessário inicializá-las antes de executar o gráfico em uma sessão. Isso é feito executando __tf.global_variables_initializer ().__
Para atualizar o valor de uma variável, simplesmente executamos uma operação de atribuição que atribui um valor à variável:

In [48]:
inicia_valor = tf.Variable(1)


const = tf.constant(1)


novo_valor = tf.add(inicia_valor , const)

atualizado = tf.assign(inicia_valor , novo_valor)

modelo = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(modelo)
    print('O valor atualizado e {}'.format(sess.run(atualizado)))


O valor atualizado e 2


# Placeholders

Agora, sabemos como manipular variáveis dentro do TensorFlow, mas o que é sobre a alimentação de dados fora de um modelo TensorFlow?
Se você deseja alimentar dados para um modelo TensorFlow de fora de um modelo, você precisará usar marcadores de posição.
Então, quais são esses espaços reservados e o que eles fazem?
Os marcadores de posição podem ser vistos como "furos" em seu modelo, "furos" aos quais você passará os dados, você pode criá-los usando
tf.placeholder (tipo de dados), onde o tipo de dados especifica o tipo de dados (inteiros, pontos flutuantes, strings, booleanos), juntamente com os bits de precisão (8, 16, 32, 64).
A definição de cada tipo de dados com a respectiva sintaxe python é definida como:

|Data type	|Python type|Description|
| --------- | --------- | --------- |
|DT_FLOAT	|tf.float32	|32 bits floating point.|
|DT_DOUBLE	|tf.float64	|64 bits floating point.|
|DT_INT8	|tf.int8	|8 bits signed integer.|
|DT_INT16	|tf.int16	|16 bits signed integer.|
|DT_INT32	|tf.int32	|32 bits signed integer.|
|DT_INT64	|tf.int64	|64 bits signed integer.|
|DT_UINT8	|tf.uint8	|8 bits unsigned integer.|
|DT_STRING	|tf.string	|Variable length byte arrays. Each element of a Tensor is a byte array.|
|DT_BOOL	|tf.bool	|Boolean.|
|DT_COMPLEX64	|tf.complex64	|Complex number made of two 32 bits floating points: real and imaginary parts.|
|DT_COMPLEX128	|tf.complex128	|Complex number made of two 64 bits floating points: real and imaginary parts.|
|DT_QINT8	|tf.qint8	|8 bits signed integer used in quantized Ops.|
|DT_QINT32	|tf.qint32	|32 bits signed integer used in quantized Ops.|
|DT_QUINT8	|tf.quint8	|8 bits unsigned integer used in quantized Ops.|


In [50]:
# usando o placeholder 

In [51]:
a  = tf.placeholder('float')


In [52]:
y = a * 4

In [54]:
sess = tf.Session()
sess.run(y, feed_dict={a:3.5})


14.0

# Operations

In [55]:
a = tf.constant([5])
b = tf.constant([10])

resultado = tf.subtract(a , b)
sess = tf.Session()
sess.run(resultado)


array([-5], dtype=int32)